import org.junit.Test;

import Guitar.Dao.GuitarDaoImpl;
import Guitar.Entity.Guitar;
import Guitar.Entity.GuitarSpec;
import Guitar.Entity.Inventory;
import Guitar.service.GuitarService;

import static org.junit.Assert.*;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by '浪费' at '17-5-9 下午8:31' with Gradle 2.11
 *
 * @author 浪费, @date 17-5-9 下午8:31
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    
  @Test  public void Testsearch() throws SQLException{
	 Guitar guitar=new Guitar();
	 GuitarSpec guitarspec=new GuitarSpec();
	 guitar.setPrice(0);
	 guitar.setId(0);
	 guitarspec.setBuilder("美国");
	 guitarspec.setTopwood("红木");
	 guitarspec.setBackwood("");;
	 guitarspec.setModel("");
	 guitarspec.setType("");
   	 Inventory inventory=new Inventory();
   	 GuitarService gs=new GuitarService();
   	 gs.setGuitardao(new GuitarDaoImpl());
   	 ResultSet rs=gs.getGuitardao().search(guitar,guitarspec);
   	 while(rs.next()){
   		 System.out.println(rs.getInt(1));
   		 System.out.println(rs.getString(2));
   		 System.out.println(rs.getString(3));
   		 System.out.println(rs.getString(5));
   		 System.out.println(rs.getInt(4));
   		 System.out.println(rs.getString(6));
   		 System.out.println(rs.getString(7));
   	 }

    }
}
